[env]
RUST_BACKTRACE = "0"
DATABASE_URL="sqlite://db.sqlite?mode=rwc"

[alias]
run_dev = [
    "watch",
    "-w", "src/",
    # "-w", "migration/",
    "-w", "Cargo.toml",
    "-x", "run",
    # "-s", "cargo run -- -l 8888",
]